import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next';
import { ReduxProvider } from '@/redux/Provider';
import { ToastContainer } from 'react-toastify';
import { Inter } from 'next/font/google';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <body className={`${inter.className} bg-grey-500 pt-24 text-grey-100`}>
          <Header />
          {children}
          <ToastContainer />
        </body>
      </html>
    </ReduxProvider>
  );
}
